---
galaxy_info:
  role_name: etcd
  author: pigsty-lite
  description: Install and configure etcd cluster for use as Patroni DCS.
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions: ["10"]
dependencies: []
