---
- name: Install custom patroni-rest firewalld service
  ansible.builtin.copy:
    content: "{{ lookup('ansible.builtin.file', role_path + '/../../files/firewalld/services/patroni-rest.xml') }}"
    dest: /etc/firewalld/services/patroni-rest.xml
    owner: root
    group: root
    mode: "0644"
  register: patroni_fw_svc

- name: Reload firewalld if patroni-rest definition changed  # noqa: no-handler
  ansible.builtin.command: firewall-cmd --reload
  when: patroni_fw_svc.changed
  changed_when: true

- name: Open patroni-rest in default zone
  ansible.posix.firewalld:
    service: "{{ patroni_firewalld_service_name }}"
    permanent: true
    state: enabled
    immediate: true
    zone: "{{ patroni_firewalld_zone }}"
