---
- name: Install and base-configure Grafana
  ansible.builtin.include_role:
    name: grafana.grafana.grafana
  vars:
    grafana_ini:
      server:
        http_addr: "{{ grafana_listen_address }}"
        http_port: "{{ grafana_port }}"
        root_url: "{{ grafana_root_url }}"
        serve_from_sub_path: "{{ grafana_serve_from_sub_path }}"
      database:
        type: sqlite3
      security:
        admin_user: "{{ grafana_admin_user }}"
        admin_password: "{{ grafana_admin_password }}"
