---
preflight_required_os_family: "RedHat"
preflight_required_os_major: 10
preflight_required_packages:
  - firewalld
  - policycoreutils
  - policycoreutils-python-utils
preflight_required_selinux_mode: "{{ selinux_required_mode | default('Enforcing') }}"
preflight_warn_only_on_block_devices: true
