---
galaxy_info:
  role_name: postgres
  author: pigsty-lite
  description: Install PostgreSQL from PGDG; do not initialize the cluster.
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions: ["10"]
dependencies: []
