---
- name: Reload PostgreSQL
  community.postgresql.postgresql_query:
    query: "SELECT pg_reload_conf()"
    login_unix_socket: "{{ provision_dbsu_socket_dir }}"
    login_user: "{{ provision_dbsu }}"
    db: postgres
  become: true
  become_user: "{{ provision_dbsu }}"
  delegate_to: "{{ provision_leader_host }}"
  run_once: true
