---
- name: Install and configure VictoriaMetrics single-node
  ansible.builtin.include_role:
    name: victoriametrics.cluster.vmsingle
  vars:
    victoriametrics_data_dir: "{{ monitoring_server_vmsingle_data_dir }}"
    victoriametrics_retention_period_months: "{{ monitoring_server_vmsingle_retention }}"
    victoriametrics_service_args: >-
      {{ victoriametrics_service_args
         | combine({'httpListenAddr': monitoring_server_vmsingle_listen}) }}
