{
 "title": "Node Instance",
 "description": "Adapted from Pigsty node/node-instance.json @745a4ea (Apache-2.0) for pigsty-lite native metrics.",
 "tags": [ "node" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"node\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"node\",cluster=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "x": 0, "y": 0, "w": 24, "h": 1 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{instance=~\"$instance\",cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(count without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))))",
     "legendFormat": "Core"
    },
    {
     "expr": "sum by(instance) (node_memory_MemTotal_bytes{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Mem"
    },
    {
     "expr": "sum by(instance) (node_memory_SwapTotal_bytes{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Swap"
    },
    {
     "expr": "sum(max by(mountpoint)(node_filesystem_size_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}))",
     "legendFormat": "Disk"
    },
    {
     "expr": "sum(node_filesystem_size_bytes{device=~\"/dev/(nvme.*|dfa.*)\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "NVMe"
    },
    {
     "expr": "- absent(node_network_speed_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}) OR max by(instance) (node_network_speed_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}) * 8",
     "legendFormat": "Link"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(avg without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_load1{cluster=~\"$cluster\",instance=~\"$instance\"} / (count without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))))))",
     "legendFormat": "load1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - node_memory_MemAvailable_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} / node_memory_MemTotal_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}))",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} / node_filesystem_size_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"}))",
     "legendFormat": "Space"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filefd_allocated{cluster=~\"$cluster\",instance=~\"$instance\"} / node_filefd_maximum{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "FD"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 22, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max((1 - (node_filesystem_files_free{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} / node_filesystem_files{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"})))",
     "legendFormat": "iNode"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(((rate(node_disk_reads_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) + (rate(node_disk_writes_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
     "legendFormat": "IOPS"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum without(device) ((rate(node_disk_read_bytes_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) + (sum without(device) ((rate(node_disk_written_bytes_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))",
     "legendFormat": "Disk IO"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((sum without(device) ((rate(node_network_transmit_bytes_total{device!~\"lo|bond.*\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) + (sum without(device) ((rate(node_network_receive_bytes_total{device!~\"lo|bond.*\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))",
     "legendFormat": "Net Traff"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(rate((node_netstat_TcpExt_ListenOverflows{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_netstat_TcpExt_ListenDrops{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_netstat_Tcp_InErrs{cluster=~\"$cluster\",instance=~\"$instance\"}\n)[1m:]))",
     "legendFormat": "TCP Errs"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((rate(node_netstat_Tcp_RetransSegs{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / (rate(node_netstat_Tcp_OutSegs{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
     "legendFormat": "Retrans"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(node_timex_sync_status{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Time Sync"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} / node_filesystem_size_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ device }} → {{ mountpoint }}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(avg without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))))",
     "legendFormat": "Realtime"
    },
    {
     "expr": "(avg_over_time((avg without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))))[1m:]))",
     "legendFormat": "1m"
    },
    {
     "expr": "(avg_over_time((avg without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))))[5m:]))",
     "legendFormat": "5m"
    },
    {
     "expr": "(avg_over_time((avg without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))))[15m:]))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "Processor",
   "type": "row",
   "gridPos": { "x": 0, "y": 19, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(avg without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))))",
       "legendFormat": "Realtime"
      },
      {
       "expr": "(avg_over_time((avg without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))))[1m:]))",
       "legendFormat": "1m"
      },
      {
       "expr": "(avg_over_time((avg without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))))[5m:]))",
       "legendFormat": "5m"
      },
      {
       "expr": "(avg_over_time((avg without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))))[15m:]))",
       "legendFormat": "15m"
      }
     ]
    },
    {
     "title": "CPU Time by State (per Second)",
     "type": "timeseries",
     "description": "Sum of all state will approximately to the number of cpu core",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by(mode) (rate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{ mode }}"
      },
      {
       "expr": "sum((count without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))))))",
       "legendFormat": "CPU Count"
      }
     ]
    },
    {
     "title": "Core Usage Realtime",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 16, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg_over_time((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))[1m:])",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "(avg_over_time((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))))[15m:]))",
       "legendFormat": "C{{ cpu }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Schedule",
   "type": "row",
   "gridPos": { "x": 0, "y": 20, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load (1m, 5m, 15m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_load1{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "load1"
      },
      {
       "expr": "node_load5{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "load5"
      },
      {
       "expr": "node_load15{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "load15"
      }
     ]
    },
    {
     "title": "Normalized Load (1m, 5m, 15m)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(node_load1{cluster=~\"$cluster\",instance=~\"$instance\"} / (count without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))))))",
       "legendFormat": "load1"
      },
      {
       "expr": "(node_load5{cluster=~\"$cluster\",instance=~\"$instance\"} / (count without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))))))",
       "legendFormat": "load5"
      },
      {
       "expr": "(node_load15{cluster=~\"$cluster\",instance=~\"$instance\"} / (count without(cpu) ((1 - (sum without(mode) ((irate(node_cpu_seconds_total{mode=\"idle\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))) / (sum without(mode) ((irate(node_cpu_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))))))",
       "legendFormat": "load15"
      }
     ]
    },
    {
     "title": "Scheduled Timeslices",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(node_schedstat_timeslices_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "title": "Schedule Waiting Time",
     "type": "timeseries",
     "description": "How long processes had to be wait to be scheduled on that CPU.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(node_schedstat_waiting_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "CPU {{ cpu }}"
      }
     ]
    },
    {
     "title": "Process State",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_procs_running{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Running"
      },
      {
       "expr": "node_procs_blocked{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Blocked"
      }
     ]
    },
    {
     "title": "Context Switch",
     "type": "timeseries",
     "description": "Context switch rate 1m",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(node_context_switches_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Ctx Switch"
      }
     ]
    },
    {
     "title": "Fork",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(node_forks_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Fork"
      }
     ]
    },
    {
     "title": "Interrupt",
     "type": "timeseries",
     "description": "Interrupt Rate 1m",
     "gridPos": { "h": 5, "w": 14, "x": 10, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(node_intr_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Interrupt"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "x": 0, "y": 21, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory & Swap Usage",
     "type": "timeseries",
     "description": "Memory Usage : 1 - mem_avail / mem_total",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1 - node_memory_MemAvailable_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} / node_memory_MemTotal_bytes{cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "Memory"
      },
      {
       "expr": "(1 - node_memory_SwapFree_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} / node_memory_SwapTotal_bytes{cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "Swap"
      }
     ]
    },
    {
     "title": "Committed Ratio",
     "type": "timeseries",
     "description": "Commit Ratio = CommittedAS / CommitLimit",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} / node_memory_CommitLimit_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Commit Ratio"
      }
     ]
    },
    {
     "title": "Memory Structure: App/Kernel",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} \n* node_memory_HugePages_Total{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "HugePage"
      },
      {
       "expr": "(node_memory_KernelStack_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_VmallocUsed_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_HardwareCorrupted_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_PageTables_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_Slab_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_PageTables_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "Kernel"
      },
      {
       "expr": "(node_memory_MemTotal_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} -\n(node_memory_KernelStack_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_VmallocUsed_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_HardwareCorrupted_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_PageTables_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_Slab_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_PageTables_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}) - \nnode_memory_Buffers_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} -\n(node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} * node_memory_HugePages_Total{cluster=~\"$cluster\",instance=~\"$instance\"}) -\n(node_memory_Cached_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} - node_memory_Mapped_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} ) -\nnode_memory_MemFree_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}\n)",
       "legendFormat": "Application RSS"
      },
      {
       "expr": "node_memory_Cached_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} - node_memory_Mapped_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_MemFree_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_MemTotal_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Committed",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "node_memory_Committed_AS_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Committed"
      },
      {
       "expr": "node_memory_CommitLimit_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Memory Structure: PageCache",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} \n* node_memory_HugePages_Total{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "HugePage"
      },
      {
       "expr": "node_memory_KernelStack_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_VmallocUsed_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_HardwareCorrupted_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_PageTables_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_Slab_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_PageTables_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Kernel"
      },
      {
       "expr": "node_memory_Cached_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Cache"
      },
      {
       "expr": "node_memory_Buffers_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Buffer"
      },
      {
       "expr": "node_memory_AnonPages_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Anon"
      },
      {
       "expr": "node_memory_MemFree_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_MemTotal_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Memory Structure: LRU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} \n* node_memory_HugePages_Total{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "HugePage"
      },
      {
       "expr": "node_memory_KernelStack_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_VmallocUsed_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_HardwareCorrupted_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_PageTables_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_Slab_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} +\nnode_memory_PageTables_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Kernel"
      },
      {
       "expr": "node_memory_Active_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Active"
      },
      {
       "expr": "node_memory_Inactive_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "InActive"
      },
      {
       "expr": "node_memory_Unevictable_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Unevictable"
      },
      {
       "expr": "node_memory_MemFree_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_MemTotal_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Memory Structure: Kernel",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_KernelStack_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "KernelStack"
      },
      {
       "expr": "node_memory_VmallocUsed_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "VmallocUsed"
      },
      {
       "expr": "node_memory_HardwareCorrupted_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "HardwareCorrupted"
      },
      {
       "expr": "node_memory_PageTables_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "PageTable"
      },
      {
       "expr": "node_memory_Slab_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Slab"
      }
     ]
    },
    {
     "title": "Mem Struct: LRU Details",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Inactive_file_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Inactive-File"
      },
      {
       "expr": "node_memory_Inactive_anon_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Inactive-Anon"
      },
      {
       "expr": "node_memory_Active_file_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Active-File"
      },
      {
       "expr": "node_memory_Active_anon_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Active-Anon"
      },
      {
       "expr": "node_memory_Unevictable_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Unevictable"
      }
     ]
    },
    {
     "title": "HugePage Allocation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} * node_memory_HugePages_Free{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} * (node_memory_HugePages_Total{cluster=~\"$cluster\",instance=~\"$instance\"} - node_memory_HugePages_Free{cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "Alloc"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} * node_memory_HugePages_Rsvd{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"} * node_memory_HugePages_Total{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "PageSize"
      },
      {
       "expr": "node_memory_HugePages_Total{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Total Pages"
      },
      {
       "expr": "(node_memory_HugePages_Total{cluster=~\"$cluster\",instance=~\"$instance\"} - node_memory_HugePages_Free{cluster=~\"$cluster\",instance=~\"$instance\"} + node_memory_HugePages_Rsvd{cluster=~\"$cluster\",instance=~\"$instance\"}) / node_memory_HugePages_Total{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Alloc%"
      },
      {
       "expr": "node_memory_HugePages_Free{cluster=~\"$cluster\",instance=~\"$instance\"} * node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Free"
      },
      {
       "expr": "node_memory_HugePages_Rsvd{cluster=~\"$cluster\",instance=~\"$instance\"} * node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Reserved"
      },
      {
       "expr": "(node_memory_HugePages_Total{cluster=~\"$cluster\",instance=~\"$instance\"} - node_memory_HugePages_Free{cluster=~\"$cluster\",instance=~\"$instance\"}) * node_memory_Hugepagesize_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Alloc"
      }
     ]
    }
   ]
  },
  {
   "title": "VMSTAT",
   "type": "row",
   "gridPos": { "x": 0, "y": 22, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Page In/Out Rate",
     "type": "timeseries",
     "description": "Rate of pages in/out/swapin/swapout",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(node_vmstat_pgpgin{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▲PageIn"
      },
      {
       "expr": "- (rate(node_vmstat_pgpgout{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▼PageOut"
      }
     ]
    },
    {
     "title": "Swap In/Out Rate",
     "type": "timeseries",
     "description": "Rate of pages in/out/swapin/swapout",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(node_vmstat_pswpin{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▲SwapIn"
      },
      {
       "expr": "- (rate(node_vmstat_pswpout{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▼SwapOut"
      }
     ]
    },
    {
     "title": "Major Page Fault",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(rate(node_vmstat_pgmajfault{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "PageFault"
      }
     ]
    },
    {
     "title": "Page Fault",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(rate(node_vmstat_pgfault{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "PageFault"
      }
     ]
    },
    {
     "title": "Writeback",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Writeback_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Writeback"
      }
     ]
    },
    {
     "title": "Dirty Bytes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_memory_Dirty_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Writeback"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "x": 0, "y": 23, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk iostat",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max by(device) (irate(node_disk_io_time_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "util"
      },
      {
       "expr": "max by(device) (irate(node_disk_io_time_weighted_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "queue"
      },
      {
       "expr": "max by(device) (irate(node_disk_reads_completed_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "r/s"
      },
      {
       "expr": "max by(device) (irate(node_disk_writes_completed_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "w/s"
      },
      {
       "expr": "max by(device) (irate(node_disk_reads_merged_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "mr/s"
      },
      {
       "expr": "max by(device) (irate(node_disk_writes_merged_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "mw/s"
      },
      {
       "expr": "max by(device) ((rate(node_disk_read_bytes_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "rb/s"
      },
      {
       "expr": "max by(device) (irate(node_disk_written_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "wb/s"
      },
      {
       "expr": "max by(device) (((rate(node_disk_read_time_seconds_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / (rate(node_disk_reads_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "r_await"
      },
      {
       "expr": "max by(device) (((rate(node_disk_write_time_seconds_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / (rate(node_disk_writes_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "w_await"
      },
      {
       "expr": "max by(device) (((rate(node_disk_read_bytes_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / (rate(node_disk_reads_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "rreq-sz"
      },
      {
       "expr": "max by(device) (((rate(node_disk_written_bytes_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / (rate(node_disk_writes_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "wreq-sz"
      }
     ]
    },
    {
     "title": "Read/Write IOPS",
     "type": "timeseries",
     "description": "▲ for read IOPS, ▼ for write IOPS",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(rate(node_disk_reads_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- (rate(node_disk_writes_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Read/Write Bandwidth",
     "type": "timeseries",
     "description": "▲ for read bandwidth, ▼ for write bandwidth",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(rate(node_disk_read_bytes_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- (rate(node_disk_written_bytes_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Reads/Writes Merged Ratio",
     "type": "timeseries",
     "description": "Merged ratio of read / write requests\n▲ for read ▼ for write",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "((rate(node_disk_reads_merged_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / ((rate(node_disk_reads_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) + (rate(node_disk_reads_merged_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- ((rate(node_disk_writes_merged_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / ((rate(node_disk_writes_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) + (rate(node_disk_writes_merged_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Read/Write Request Size (areq-sz)",
     "type": "timeseries",
     "description": "▲ for read, ▼ for write, Showing I/O pattern",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "((rate(node_disk_read_bytes_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / (rate(node_disk_reads_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- ((rate(node_disk_written_bytes_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / (rate(node_disk_writes_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Read/Write Await Time",
     "type": "timeseries",
     "description": "▲ for read rt, ▼ for write rt",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "((rate(node_disk_read_time_seconds_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / (rate(node_disk_reads_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- ((rate(node_disk_write_time_seconds_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / (rate(node_disk_writes_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Average Service Time (svctm)",
     "type": "timeseries",
     "description": "▲ for read rt, ▼ for write rt",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "(((rate(node_disk_read_time_seconds_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) + (rate(node_disk_write_time_seconds_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))) / ((rate(node_disk_reads_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) + (rate(node_disk_writes_completed_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Instant Queue Size",
     "type": "timeseries",
     "description": "Number of items which were in the queue at the sampling time point",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_disk_io_now{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ device }}"
      }
     ]
    },
    {
     "title": "Average Queue Size",
     "type": "timeseries",
     "description": "average number of operations waiting to be serviced.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(rate(node_disk_io_time_weighted_seconds_total{device=~\"[a-z0-9A-Z-_]+\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "row",
   "gridPos": { "x": 0, "y": 24, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "node_filesystem_size_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Total"
      },
      {
       "expr": "max by(device) (node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "Avail"
      },
      {
       "expr": "max by(device) (node_filesystem_size_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} - node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "Used"
      },
      {
       "expr": "max by(device) ((1 - node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} / node_filesystem_size_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"}))",
       "legendFormat": "Usage"
      },
      {
       "expr": "max by(device) (node_filesystem_files{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "iNodes"
      },
      {
       "expr": "max by(device) (node_filesystem_files_free{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "iNode Free"
      },
      {
       "expr": "max by(device) ((node_filesystem_files{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} - node_filesystem_files_free{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"}))",
       "legendFormat": "iNode Used"
      },
      {
       "expr": "max by(device) ((1 - (node_filesystem_files_free{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} / node_filesystem_files{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"})))",
       "legendFormat": "iNode Usage"
      },
      {
       "expr": "min by(device) (node_filesystem_readonly{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "iNode Usage"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} / node_filesystem_size_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Avail Space 1D Prediction",
     "type": "stat",
     "description": "Prediction of avail filesystem space a day later!",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(predict_linear(node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"}[1h], 86400))",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "iNode Usage",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - (node_filesystem_files_free{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} / node_filesystem_files{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"}))",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Device Error",
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "node_filesystem_device_error{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Derive 1h",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "(deriv(node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"}[1h]))",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1 - node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} / node_filesystem_size_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "Space Exhaust Estimate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg_over_time((clamp(node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"} / - (deriv(node_filesystem_avail_bytes{fstype!~\"(n|root|tmp)fs.*\",cluster=~\"$cluster\",instance=~\"$instance\"}[1h])), -1, 126230400))[5m:])",
       "legendFormat": "{{ mountpoint }}"
      }
     ]
    },
    {
     "title": "FD Usage",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Used"
      },
      {
       "expr": "(node_filefd_allocated{cluster=~\"$cluster\",instance=~\"$instance\"} / node_filefd_maximum{cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "Usage"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "x": 0, "y": 25, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_network_info{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "INFO"
      },
      {
       "expr": "max by(device) (node_network_mtu_bytes{cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "MTU"
      },
      {
       "expr": "max by(device) (node_network_speed_bytes{cluster=~\"$cluster\",instance=~\"$instance\"}) * 8",
       "legendFormat": "Link Speed"
      },
      {
       "expr": "min by(device) ((rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "Transmit"
      },
      {
       "expr": "min by(device) ((rate(node_network_receive_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "Receive"
      },
      {
       "expr": "min by(device) ((rate(node_network_transmit_packets_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "TX PPS"
      },
      {
       "expr": "min by(device) ((rate(node_network_receive_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "RX bandwidth"
      }
     ]
    },
    {
     "title": "Transmit/Receive Packets",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "(sum without(device) ((rate(node_network_transmit_packets_total{device!~\"lo|bond.*\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "▲TX"
      },
      {
       "expr": "- (sum without(device) ((rate(node_network_receive_packets_total{device!~\"lo|bond.*\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "▼RX"
      }
     ]
    },
    {
     "title": "Transmit/Receive Bandwidth",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(sum without(device) ((rate(node_network_transmit_bytes_total{device!~\"lo|bond.*\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- (sum without(device) ((rate(node_network_receive_bytes_total{device!~\"lo|bond.*\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))))",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Transmit/Receive Packets (Interface)",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "(rate(node_network_transmit_packets_total{device!=\"lo\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- (rate(node_network_receive_packets_total{device!=\"lo\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▼{{ device }}"
      }
     ]
    },
    {
     "title": "Transmit/Receive Bandwidth (Interface)",
     "type": "timeseries",
     "description": "▲ for transmit (out) and ▼ for receive (in)",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "(rate(node_network_transmit_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▲{{ device }}"
      },
      {
       "expr": "- (rate(node_network_receive_bytes_total{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▼{{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "row",
   "gridPos": { "x": 0, "y": 26, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCP Segments",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "(rate(node_netstat_Tcp_InSegs{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▼in"
      },
      {
       "expr": "- (rate(node_netstat_Tcp_OutSegs{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "▲out"
      }
     ]
    },
    {
     "title": "UDP Datagrams",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "rate(node_netstat_Udp_InDatagrams{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "▼in"
      },
      {
       "expr": "- rate(node_netstat_Udp_OutDatagrams{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "▲out"
      }
     ]
    },
    {
     "title": "TCP Connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_netstat_Tcp_CurrEstab{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Current"
      }
     ]
    },
    {
     "title": "TCP Socket Stat",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_sockstat_TCP_inuse{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Using"
      },
      {
       "expr": "- node_sockstat_TCP_tw{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Time Wait"
      }
     ]
    },
    {
     "title": "TCP Open",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(node_netstat_Tcp_ActiveOpens{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "active"
      },
      {
       "expr": "- rate(node_netstat_Tcp_PassiveOpens{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "passive"
      }
     ]
    },
    {
     "title": "TCP Retransmit",
     "type": "timeseries",
     "description": "TCP retransmission segments and rate",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "(rate(node_netstat_Tcp_RetransSegs{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
       "legendFormat": "Retrans Segs"
      },
      {
       "expr": "((rate(node_netstat_Tcp_RetransSegs{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / (rate(node_netstat_Tcp_OutSegs{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))",
       "legendFormat": "Rate"
      }
     ]
    },
    {
     "title": "TCP Errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(node_netstat_TcpExt_ListenOverflows{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "Listen Overflows"
      },
      {
       "expr": "irate(node_netstat_TcpExt_ListenDrops{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "Listen Drop"
      },
      {
       "expr": "irate(node_netstat_Tcp_RetransSegs{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "Retrans"
      },
      {
       "expr": "irate(node_netstat_Tcp_InErrs{cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
       "legendFormat": "In Error"
      }
     ]
    }
   ]
  },
  {
   "title": "Misc",
   "type": "row",
   "gridPos": { "x": 0, "y": 27, "w": 24, "h": 1 },
   "collapsed": true,
   "panels": [
    {
     "type": "stat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max by(instance) (node_timex_sync_status{cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "max by(instance) (node_timex_status{cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "max by(instance) (node_timex_offset_seconds{cluster=~\"$cluster\",instance=~\"$instance\"})",
       "legendFormat": "{{instance}}"
      },
      {
       "expr": "max by(instance) (node_timex_frequency_adjustment_ratio{cluster=~\"$cluster\",instance=~\"$instance\"}) - 1",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Time Offset (s)",
     "type": "timeseries",
     "description": "node_timex_offset_seconds: This metric represents the current time offset in seconds between the system clock and a reference time source.",
     "gridPos": { "h": 6, "w": 9, "x": 6, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_offset_seconds{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Offset"
      }
     ]
    },
    {
     "title": "Time Sync Status & Clock Freq Adjust%",
     "type": "timeseries",
     "description": "node_timex_sync_status: This metric indicates the synchronization status of the timekeeping system. if != 1 then time out of sync.\n\nnode_timex_frequency_adjustment_ratio: It indicates the ratio of the current frequency adjustment to the nominal frequency, used to keep the system clock synchronized.",
     "gridPos": { "h": 6, "w": 9, "x": 15, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_sync_status{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "Synced"
      },
      {
       "expr": "node_timex_frequency_adjustment_ratio{cluster=~\"$cluster\",instance=~\"$instance\"} - 1",
       "legendFormat": "Adjust"
      }
     ]
    },
    {
     "title": "Node Exporter Duration",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_scrape_collector_duration_seconds{cluster=~\"$cluster\",instance=~\"$instance\"}",
       "legendFormat": "{{ collector }}"
      }
     ]
    }
   ]
  }
 ]
}