{
 "title": "PostgreSQL pgBouncer",
 "description": "Adapted from Pigsty pgsql/pgsql-pgbouncer.json @745a4ea (Apache-2.0) for pigsty-lite native metrics.",
 "tags": [ "postgresql" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"pgbouncer\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"pgbouncer\",cluster=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "QPS / Query RT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS Seasonality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[5m]))",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[5m] offset 1d))",
     "legendFormat": "{{instance}} (1d ago)"
    },
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[5m] offset 2d))",
     "legendFormat": "{{instance}} (2d ago)"
    }
   ]
  },
  {
   "title": "Average Queries per Xact",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_sql_transactions_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average Queries per Commit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / on (cluster, instance) sum by (cluster, instance) (rate(pg_stat_database_xact_commit{cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "timeseries",
   "description": "pgBouncer Queries per second according to last 1m, 5m, 15m",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m]))",
     "legendFormat": "1m"
    },
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[5m]))",
     "legendFormat": "5m"
    },
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[15m]))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "RT",
   "type": "timeseries",
   "description": "pgBouncer query average response time in last 1m, 5m, 15m",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m]))",
     "legendFormat": "1m"
    },
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[5m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[5m]))",
     "legendFormat": "5m"
    },
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[15m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[15m]))",
     "legendFormat": "15m"
    }
   ]
  },
  {
   "title": "QPS Divergence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[5m:]) / stddev_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[5m:])) ^ 2"
    }
   ]
  },
  {
   "title": "RT Divergence",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[5m:]) / stddev_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[5m:])) ^ 2"
    }
   ]
  },
  {
   "title": "QPS Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m]))",
     "legendFormat": "QPS"
    },
    {
     "expr": "avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:])",
     "legendFormat": "Mean"
    },
    {
     "expr": "avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:]) + stddev_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:])",
     "legendFormat": "+1σ"
    },
    {
     "expr": "avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:]) - stddev_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:])",
     "legendFormat": "-1σ"
    },
    {
     "expr": "avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:]) + 3 * stddev_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:]) - 3 * stddev_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:])",
     "legendFormat": "-3σ"
    }
   ]
  },
  {
   "title": "RT Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m]))",
     "legendFormat": "Query RT"
    },
    {
     "expr": "avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:])",
     "legendFormat": "Mean"
    },
    {
     "expr": "avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:]) + stddev_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:])",
     "legendFormat": "+1σ"
    },
    {
     "expr": "avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:]) - stddev_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:])",
     "legendFormat": "-1σ"
    },
    {
     "expr": "avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:]) + 3 * stddev_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:])",
     "legendFormat": "+3σ"
    },
    {
     "expr": "avg_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:]) - 3 * stddev_over_time((sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])))[15m:])",
     "legendFormat": "-3σ"
    }
   ]
  },
  {
   "title": "QPS by Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance, database) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[5m]))",
     "legendFormat": "{{database}}"
    },
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[5m]))",
     "legendFormat": "{{instance}} total"
    }
   ]
  },
  {
   "title": "QPS by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[5m]))",
     "legendFormat": "{{cluster}} total"
    },
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[5m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Query RT by Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m]))",
     "legendFormat": "{{instance}} total"
    },
    {
     "expr": "sum by (cluster, instance, database) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance, database) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m]))",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Query RT by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (cluster) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m]))",
     "legendFormat": "{{cluster}} total"
    },
    {
     "expr": "sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_duration_seconds_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m])) / sum by (cluster, instance) (rate(pgbouncer_stats_totals_queries_pooled_total{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}[1m]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Session", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "pgBouncer Connection Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pgbouncer_databases_current_connections{cluster=~\"$cluster\",instance=~\"$instance\",name!=\"pgbouncer\"} / pgbouncer_databases_pool_size{cluster=~\"$cluster\",instance=~\"$instance\",name!=\"pgbouncer\"}",
     "legendFormat": "{{name}} / {{database}}"
    }
   ]
  },
  {
   "title": "pgBouncer Servers & Clients",
   "type": "timeseries",
   "description": "New Conn Rate/s in last Minute: Number of assignment for server assigned to client",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "-pgbouncer_pools_server_active_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"} - pgbouncer_pools_server_idle_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"} - pgbouncer_pools_server_used_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"} - pgbouncer_pools_server_testing_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"} - pgbouncer_pools_server_login_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "{{database}} / {{user}} (servers)"
    },
    {
     "expr": "pgbouncer_pools_client_active_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"} + pgbouncer_pools_client_waiting_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "{{database}} / {{user}} (clients)"
    }
   ]
  },
  {
   "title": "Max Wait",
   "type": "timeseries",
   "description": "Age in seconds of the oldest client waiting for a server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_maxwait_seconds{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "{{database}} / {{user}}"
    }
   ]
  },
  {
   "title": "pgBouncer Server State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "targets": [
    {
     "expr": "pgbouncer_pools_server_active_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "pgbouncer_pools_server_used_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "pgbouncer_pools_server_idle_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "Idle"
    },
    {
     "expr": "pgbouncer_pools_server_testing_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "Testing"
    },
    {
     "expr": "pgbouncer_pools_server_login_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "Login"
    }
   ]
  },
  {
   "title": "pgBouncer Client State",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "pgbouncer_pools_client_waiting_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "Waiting"
    }
   ]
  },
  {
   "title": "Active Server by Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "sum by (cluster, instance, database) (pgbouncer_pools_server_active_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Active Clients by Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "max by (cluster, instance, database) (pgbouncer_pools_client_active_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"})",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "title": "Active Clients",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{database}} / {{user}}"
    }
   ]
  },
  {
   "title": "Clients by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "sum by (cluster, instance, user) (pgbouncer_pools_client_active_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"})",
     "legendFormat": "{{user}}"
    }
   ]
  },
  {
   "title": "Clients by Pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "pgbouncer_pools_client_active_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"}",
     "legendFormat": "{{database}} / {{user}}"
    }
   ]
  },
  {
   "title": "Clients by Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "sum by (cluster, instance, database) (pgbouncer_pools_client_active_connections{cluster=~\"$cluster\",instance=~\"$instance\",database!=\"pgbouncer\"})",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}