{
 "title": "PostgreSQL Patroni",
 "description": "Adapted from Pigsty pgsql/pgsql-patroni.json @745a4ea (Apache-2.0) for pigsty-lite native metrics.",
 "tags": [ "postgresql" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"patroni\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"patroni\",cluster=~\"$cluster\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Patroni Members",
   "type": "table",
   "description": "Patroni member status and PostgreSQL version for the selected cluster.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (cluster,instance) (patroni_primary{cluster=~\"$cluster\",instance=~\"$instance\"}) + \nmax by (cluster,instance) (patroni_standby_leader{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance,scope) (patroni_version{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_postgres_server_version{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_is_paused{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_cluster_unlocked{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_pending_restart{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_failsafe_mode_is_active{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_xlog_paused{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_postgres_running{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (time() - patroni_dcs_last_seen{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (time() - patroni_postmaster_start_time{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (up{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Patroni Agent Health",
   "type": "timeseries",
   "description": "Whether the Patroni /metrics endpoint is reachable.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "up{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Leadership",
   "type": "timeseries",
   "description": "`patroni_primary` of this cluster ${cluster}. 1 means this member is leader of the cluster.\n\n2 `sleader` means this is a standby leader",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max by (cluster,instance) (patroni_primary{cluster=~\"$cluster\",instance=~\"$instance\"})\n+ max by (cluster,instance) (patroni_standby_leader{cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cluster Lock State",
   "type": "timeseries",
   "description": "patroni_cluster_unlocked is 1 when the cluster is unlocked.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "patroni_cluster_unlocked{cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Failsafe Activated",
   "type": "timeseries",
   "description": "`patroni_failsafe_mode_is_active` of this cluster ${cluster}. 1 means this cluster's failsafe mode is activated",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "patroni_failsafe_mode_is_active{cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Pending Restart",
   "type": "timeseries",
   "description": "`patroni_pending_restart` of this cluster ${cluster}. 1 means this member needs to be restarted to make config change effect.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "patroni_pending_restart{cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "WAL Paused",
   "type": "timeseries",
   "description": "`patroni_xlog_paused` of this cluster ${cluster} members. 1 means PostgresQL WAL is paused.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "patroni_xlog_paused{cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Patroni DCS Last Seen",
   "type": "timeseries",
   "description": "Elapsed time since Patroni last successfully contacted its distributed configuration store.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - patroni_dcs_last_seen{cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Postmaster Uptime",
   "type": "timeseries",
   "description": "now - `patroni_postmaster_start_time`.\n\nIndicate postgres restart event",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - patroni_postmaster_start_time{cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DCS Last Seen",
   "type": "stat",
   "description": "Elapsed time since Patroni last successfully contacted its distributed configuration store. Values above 20 seconds may need attention.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - patroni_dcs_last_seen{cluster=~\"$cluster\",instance=~\"$instance\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}