{
 "title": "PostgreSQL Instance",
 "description": "Adapted from Pigsty pgsql/pgsql-instance.json @745a4ea (Apache-2.0) for pigsty-lite native metrics.",
 "tags": [ "postgresql" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(up{job=\"postgres\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(up{job=\"postgres\",cluster=~\"$cluster\"}, instance)"
   },
   {
    "name": "datname",
    "label": "Database",
    "query": "label_values(pg_stat_database_numbackends{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}, datname)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Patroni Status",
   "type": "stat",
   "description": "HA Agent - Patroni Metrics",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cluster,instance) (patroni_primary{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"}) + max by (cluster,instance) (patroni_standby_leader{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance,scope) (patroni_version{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_postgres_server_version{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_is_paused{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_pending_restart{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_failsafe_mode_is_active{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (time() - patroni_dcs_last_seen{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database TPS",
   "type": "stat",
   "description": "TPS (1m) of each database on this postgres server",
   "gridPos": { "h": 7, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_xact_commit{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\",datname=~\"$datname\",datname!~\"template[0-9]\"}[1m]) + rate(pg_stat_database_xact_rollback{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\",datname=~\"$datname\",datname!~\"template[0-9]\"}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - sum by (cluster,instance) (rate(node_cpu_seconds_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\",mode=\"idle\"}[1m])) / sum by (cluster,instance) (rate(node_cpu_seconds_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Transaction Commits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster,instance) (rate(pg_stat_database_xact_commit{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Commit"
    }
   ]
  },
  {
   "title": "Transaction Rollbacks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster,instance) (rate(pg_stat_database_xact_rollback{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Rollback"
    }
   ]
  },
  {
   "title": "Connection Limit Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster,instance) (pg_stat_database_numbackends{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}) / max by (cluster,instance) (pg_settings_max_connections{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "Conn%"
    }
   ]
  },
  {
   "title": "Filesystem Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - node_filesystem_avail_bytes{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\",fstype!~\"(n|root|tmp)fs.*\"} / node_filesystem_size_bytes{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\",fstype!~\"(n|root|tmp)fs.*\"}",
     "legendFormat": "Space: {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "Active SQL Time per CPU",
   "type": "timeseries",
   "description": "PostgreSQL active SQL time divided by host CPU count over 1, 5, and 15 minutes.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (cluster,instance) (rate(pg_stat_database_active_time_seconds_total{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / on (cluster,instance) count by (cluster,instance) (count by (cluster,instance,cpu) (node_cpu_seconds_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\"}))",
     "legendFormat": "p1"
    },
    {
     "expr": "sum by (cluster,instance) (rate(pg_stat_database_active_time_seconds_total{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[5m])) / on (cluster,instance) count by (cluster,instance) (count by (cluster,instance,cpu) (node_cpu_seconds_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\"}))",
     "legendFormat": "p5"
    },
    {
     "expr": "sum by (cluster,instance) (rate(pg_stat_database_active_time_seconds_total{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[15m])) / on (cluster,instance) count by (cluster,instance) (count by (cluster,instance,cpu) (node_cpu_seconds_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\"}))",
     "legendFormat": "p15"
    }
   ]
  },
  { "title": "Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Patroni Members",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "max by (cluster,instance) (patroni_primary{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"}) + max by (cluster,instance) (patroni_standby_leader{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance,scope) (patroni_version{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_postgres_server_version{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_is_paused{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_cluster_unlocked{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_pending_restart{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_failsafe_mode_is_active{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_xlog_paused{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (patroni_postgres_running{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (time() - patroni_dcs_last_seen{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (time() - patroni_postmaster_start_time{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (cluster,instance) (up{job=\"patroni\",cluster=~\"$cluster\",instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time((1 - sum by (cluster,instance,cpu) (irate(node_cpu_seconds_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\",mode=\"idle\"}[1m])) / sum by (cluster,instance,cpu) (irate(node_cpu_seconds_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])))[1m:])",
     "legendFormat": "CPU {{ cpu }}"
    }
   ]
  },
  {
   "title": "Transaction Active Time per Transaction",
   "type": "timeseries",
   "description": "PostgreSQL active time per transaction, derived from pg_stat_database counters.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (cluster,instance) (rate(pg_stat_database_active_time_seconds_total{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])) / sum by (cluster,instance) (rate(pg_stat_database_xact_commit{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]) + rate(pg_stat_database_xact_rollback{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "instance"
    },
    {
     "expr": "sum by (cluster,instance,datname) (rate(pg_stat_database_active_time_seconds_total{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\",datname=~\"$datname\",datname!~\"template[0-9]\"}[1m])) / sum by (cluster,instance,datname) (rate(pg_stat_database_xact_commit{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\",datname=~\"$datname\",datname!~\"template[0-9]\"}[1m]) + rate(pg_stat_database_xact_rollback{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\",datname=~\"$datname\",datname!~\"template[0-9]\"}[1m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "Session",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\",datname=~\"$datname\",datname!~\"template[0-9]\"}",
     "legendFormat": "client backend @ {{ datname }}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "description": "Transactions per seconds for each database in Last 5 minutes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (datname) (rate(pg_stat_database_xact_commit{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\",datname=~\"$datname\",datname!~\"template[0-9]\"}[5m]) + rate(pg_stat_database_xact_rollback{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\",datname=~\"$datname\",datname!~\"template[0-9]\"}[5m]))",
     "legendFormat": "{{ datname }}"
    }
   ]
  },
  {
   "title": "CRUD",
   "type": "timeseries",
   "description": "Tuples fetched, inserted, updated, delete among this cluster",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (cluster,instance) (rate(pg_stat_database_tup_fetched{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "SELECT"
    },
    {
     "expr": "sum by (cluster,instance) (rate(pg_stat_database_tup_inserted{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "INSERTED"
    },
    {
     "expr": "sum by (cluster,instance) (rate(pg_stat_database_tup_updated{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "UPDATED"
    },
    {
     "expr": "sum by (cluster,instance) (rate(pg_stat_database_tup_deleted{job=\"postgres\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "DELETED"
    }
   ]
  },
  {
   "title": "Disk / Network",
   "type": "timeseries",
   "description": "R▲ for disk read bandwidth\nTX▲ for network transmit bandwidth\nRX▼ for network receive bandwidth\nW▼ for disk write bandwidth",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\",device=~\"[a-z0-9A-Z-_]+\"}[1m])",
     "legendFormat": "{{ device }}-R▲"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ device }}-TX▲"
    },
    {
     "expr": "- rate(node_network_receive_bytes_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{ device }}-RX▼"
    },
    {
     "expr": "- rate(node_disk_written_bytes_total{job=\"node\",cluster=~\"$cluster\",instance=~\"$instance\",device=~\"[a-z0-9A-Z-_]+\"}[1m])",
     "legendFormat": "{{ device }}-W▼"
    }
   ]
  }
 ]
}