---
- name: Reload nginx
  ansible.builtin.systemd:
    name: "{{ nginx_proxy_service }}"
    state: reloaded

- name: Reload firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: reloaded
