---
- name: Reload pgbouncer
  ansible.builtin.systemd:
    name: "{{ pgbouncer_service_name }}"
    state: reloaded

- name: Restart pgbouncer
  ansible.builtin.systemd:
    name: "{{ pgbouncer_service_name }}"
    state: restarted

- name: Reload firewalld
  ansible.builtin.command: firewall-cmd --reload
  changed_when: true
