FROM container-registry.oracle.com/os/oraclelinux:10

# Enable Oracle Linux repos needed for molecule packages
RUN dnf install -y oracle-epel-release-el10 \
    && dnf clean all

# Install PGDG repo
RUN dnf install -y \
    https://download.postgresql.org/pub/repos/yum/reporpms/EL-10-x86_64/pgdg-redhat-repo-latest.noarch.rpm \
    && dnf config-manager --enable pgdg-rhel10-extras \
    && dnf config-manager --disable pgdg14 pgdg15 pgdg16 pgdg17 \
    && dnf clean all

# Install all packages needed across molecule scenarios
RUN dnf install -y \
    iproute \
    man-db \
    sudo \
    firewalld \
    policycoreutils \
    policycoreutils-python-utils \
    python3-libselinux \
    python3-cryptography \
    python3-psycopg3 \
    etcd \
    patroni \
    patroni-etcd \
    postgresql18-server \
    postgresql18-contrib \
    postgresql18 \
    pgbouncer \
    haproxy \
    && dnf clean all

# Allow passwordless sudo so Ansible's become:true works without PAM password checks
RUN echo '%wheel ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/wheel-nopasswd \
    && echo 'ALL ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/all-nopasswd

CMD ["/sbin/init"]
