---
- name: Render pgbouncer.ini
  ansible.builtin.template:
    src: pgbouncer.ini.j2
    dest: "{{ pgbouncer_config_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: "0640"
  notify: Reload pgbouncer

- name: Render userlist.txt
  ansible.builtin.template:
    src: userlist.txt.j2
    dest: "{{ pgbouncer_userlist_file }}"
    owner: "{{ pgbouncer_user }}"
    group: "{{ pgbouncer_group }}"
    mode: "0600"
  notify: Reload pgbouncer
