---
galaxy_info:
  role_name: ca
  author: pigsty-lite
  description: Generate a self-signed CA on the control node.
  license: Apache-2.0
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions: ["10"]
  galaxy_tags: [postgresql, pki, ca]
dependencies: []
