---
- name: pgBackRest — server (backup_server group)
  hosts: backup_server
  become: true
  vars:
    pgbackrest_mode: server
  roles:
    - role: pgbackrest
      tags: [pgbackrest, backup]

- name: pgBackRest — client (postgres group)
  hosts: postgres
  become: true
  vars:
    pgbackrest_mode: client
  roles:
    - role: pgbackrest
      tags: [pgbackrest, backup]
