---
# pigsty-lite site.yml
- name: Import P0 preflight playbook
  import_playbook: _preflight.yml
  tags: [preflight]
- name: Import P0 CA playbook
  import_playbook: _ca.yml
  tags: [ca]
- name: Import P0 node playbook
  import_playbook: _node.yml
  tags: [repos, node, certs]
- name: Import P1 etcd playbook
  import_playbook: _etcd.yml
  tags: [etcd]
- name: Import P2a postgres install playbook
  import_playbook: _postgres_install.yml
  tags: [postgres]
- name: Import P2a patroni bootstrap playbook
  import_playbook: _postgres_bootstrap.yml
  tags: [patroni]
- name: Import P2b pgbouncer playbook
  import_playbook: _pgbouncer.yml
  tags: [pgbouncer]
- name: Import P2b haproxy playbook
  import_playbook: _haproxy.yml
  tags: [haproxy]
- name: Import P2b vip-manager playbook
  import_playbook: _vip_manager.yml
  tags: [vip_manager]
- name: Import P3 provision playbook
  import_playbook: _provision.yml
  tags: [provision]
- name: Import P4 backup client playbook
  import_playbook: _backup_client.yml
  tags: [backup]
- name: Import P4 backup store playbook
  import_playbook: _backup_store.yml
  tags: [backup]
